platform :ios, '7.0'
inhibit_all_warnings!
pod 'ViewDeck', '~> 2.2.11'
pod 'Parse'
pod 'ParseFacebookUtils', '~> 1.4.0'
pod 'SDWebImage'
pod 'UIActivityIndicator-for-SDWebImage'
pod 'TDBadgedCell'
pod 'SVProgressHUD'
pod 'FlurrySDK'
